print("Welcome to Tip Calculator!")
bill_cost = input("What was the total bill? ")
bill_cost_as_float = float(bill_cost)
tip_percentage = input("What percentage would you like to tip your host? ")
tip_percentage_as_int = int(tip_percentage)
total_bill_after_tip = round(bill_cost_as_float + (tip_percentage_as_int * .01 * bill_cost_as_float), 3)
number_of_customers = input("How many people are splitting the bill? ")
number_of_customers_as_int = int(number_of_customers)
each_pays = round(total_bill_after_tip / number_of_customers_as_int, 3)
print(f"If the check is split evenly, each person should pay {each_pays}.") 